# Generated by Django 4.2.5 on 2023-10-03 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_discussionpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussionpost',
            old_name='student',
            new_name='user',
        ),
    ]
