# Generated by Django 4.2.5 on 2023-10-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_course_duration_remove_course_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='assignments',
            field=models.ManyToManyField(blank=True, related_name='courses', to='dashboard.assignment'),
        ),
    ]
