# Generated by Django 4.2.5 on 2023-10-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_discussioncomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionpost',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='posts', to='dashboard.discussioncomment'),
        ),
    ]
