# Generated by Django 4.2.5 on 2023-10-03 23:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lessonBody',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
