# Generated by Django 4.2.5 on 2023-10-03 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_lesson_lessonbody'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lessonFiles',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
