# Generated by Django 4.2.5 on 2023-10-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_lesson_lessonfiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='choices',
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='option1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='option2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='option3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='option4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='answer',
            field=models.CharField(default='', max_length=100),
        ),
    ]
