# Generated by Django 4.2.5 on 2023-10-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_remove_multiplechoicequestion_choices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='points',
            field=models.IntegerField(default=5),
        ),
    ]
