# Generated by Django 4.2.5 on 2023-10-06 09:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_submission_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussioncomment',
            name='commentBody',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='discussionpost',
            name='description',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
