# Generated by Django 4.2.5 on 2023-11-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_remove_submission_earned_remove_submission_possible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionanswer',
            name='possible',
            field=models.IntegerField(default=0),
        ),
    ]
