# Generated by Django 4.2.5 on 2023-11-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_submission_earned_submission_possible'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='attempts',
            field=models.IntegerField(default=1),
        ),
    ]
