# Generated by Django 4.2.5 on 2023-12-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_assignment_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='weight',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(default='', max_length=100),
        ),
    ]
